# Support PaperKnife Development
github: potatameister

# Message:
# I am the lead developer of PaperKnife. Currently, I work 50 hours a week 
# for a monthly income of US$150. Developing high-quality, privacy-first 
# tools is my passion, but the financial reality is a constant challenge.
#
# Your support would directly help me cover my basic living expenses and 
# allow me to dedicate more time to this project. My goal is to raise 
# enough to cover the one-time Google Play and Apple Developer fees so 
# I can bring PaperKnife to the official app stores and reach more users.
#
# Every donation, no matter how small, makes a real difference in my life 
# and the future of this app. Thank you for supporting independent, 
# open-source software.
